services:
  # Frontend - Nginx serving static files
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "80:8080"  # Map host port 80 to container port 8080
    restart: unless-stopped
    # Add health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
